### ISSUE TITLE
Endianness problem when using SDCC

### ISSUE THREAD

**Issue by eeyrw** [IOsetting/FwLib_STC8#4]
The SDCC apply different endianness when accessing variable more than 1 byte.  The SDCC apply little-endian which is different from KEIL C51's big-endian (https://stackoverflow.com/a/2477501) . Using memory map 16bit register, like `#define PWMA_CCR4         (*(unsigned int  volatile __XDATA *)0xfedb)`, will encounter problem.  Because 16bit registers are big-endianness.

**Comment by IOsetting** [comment]
You are right. Should these 16bit registers be hidden in SDCC?

**Comment by eeyrw** [comment]
I think that making some explanation in the documentation and leaving it to developer to choose access 16bit xdata reg is better.
